version: "3.8"

services:
  minecraft:
    image: itzg/minecraft-server:java8
    ports:
      - "25565:25565"
    depends_on:
      - coreprotect-db
      - dynmap-db
      - luckperms-db
    environment:
      EULA: TRUE
      TYPE: MOHIST
      DEBUG: TRUE
      VERSION: 1.12.2
      DIFFICULTY: normal
      MEMORY: 1G
      TZ: Asia/Tokyo
      ENABLE_WHITELIST: TRUE
      ENFORCE_WHITELIST: TRUE
      COPY_CONFIG_DEST: /data
      SYNC_SKIP_NEWER_IN_DESTINATION: FALSE
    volumes:
      - minecraft:/data
      - ./configs:/config
      - ./mods:/mods:ro
      - ./plugins:/plugins:ro

  backup:
    image: itzg/mc-backup
    depends_on:
      - minecraft
    environment:
      TZ: Asia/Tokyo
      BACKUP_INTERVAL: "1h"
      RCON_HOST: minecraft
      RCON_PASSWORD: minecraft
    volumes:
      - minecraft:/data:ro
      - ./backups:/backups

  rcon:
    image: itzg/rcon
    depends_on:
      - minecraft
    ports:
      - "4326:4326"
      - "4327:4327"
    environment:
      TZ: Asia/Tokyo
      RWA_ADMIN: TRUE
      RWA_USERNAME: administrator
      RWA_PASSWORD: administrator
      RWA_RCON_HOST: minecraft
      RWA_RCON_PASSWORD: minecraft
    volumes:
      - rcon:/opt/rcon-web-admin/db

  coreprotect-db:
    image: mysql:5.7
    environment:
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: coreprotect
      MYSQL_DATABASE: coreprotect
      MYSQL_USER: coreprotect
      MYSQL_PASSWORD: coreprotect
    volumes:
      - coreprotect-db:/var/lib/mysql

  dynmap-db:
    image: mysql:5.7
    environment:
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: dynmap
      MYSQL_DATABASE: dynmap
      MYSQL_USER: dynmap
      MYSQL_PASSWORD: dynmap
    volumes:
      - dynmap-db:/var/lib/mysql

  luckperms-db:
    image: mysql:5.7
    environment:
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: luckperms
      MYSQL_DATABASE: luckperms
      MYSQL_USER: luckperms
      MYSQL_PASSWORD: luckperms
    volumes:
      - luckperms-db:/var/lib/mysql

volumes:
  minecraft:
  rcon:
  coreprotect-db:
  dynmap-db:
  luckperms-db:
